FROM golang:1.24.5-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /guitar-shop-api

FROM alpine:latest

RUN apk add --no-cache tzdata 

COPY --from=builder /guitar-shop-api /guitar-shop-api

EXPOSE 8080
CMD ["/guitar-shop-api"]