FROM golang:1.24-alpine AS builder

RUN apk add --no-cache git ca-certificates

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# Собираем оба бинарника в /bin
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /bin/guitar-api ./cmd/server
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /bin/guitar-cli ./cmd/cli

FROM alpine:latest
RUN apk add --no-cache tzdata ca-certificates

COPY --from=builder /bin/guitar-api /bin/
COPY --from=builder /bin/guitar-cli /bin/
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

WORKDIR /app
EXPOSE 8080
CMD ["guitar-api"]